// 4/9/2026 - added Camera

namespace O3DS.Data;

enum Direction : byte { None = 0, Left, Right, Forward, Back, Up, Down }

struct Matrix {
  m00:float;
  m01:float;
  m02:float;
  m03:float;
  m10:float;
  m11:float;
  m12:float;
  m13:float;
  m20:float;
  m21:float;
  m22:float;
  m23:float;
  m30:float;
  m31:float;
  m32:float;
  m33:float;
}

struct Translation {
  x:float;
  y:float;
  z:float;
}

struct Rotation {
  x:float;
  y:float;
  z:float;
  w:float;
}

struct Scale {
  x:float;
  y:float;
  z:float;
}

struct TranslationUpdate {
  x:float;
  y:float;
  z:float;
  i:int;
}

struct RotationUpdate {
  x:float;
  y:float;
  z:float;
  w:float;
  i:int;
}

struct ScaleUpdate {
  x:float;
  y:float;
  z:float;
  i:int;
}


enum Component : byte { Translation, Rotation, Scale, Matrix }

table Transform { 
  parent:int;
  name:string;
  translation:Translation;
  rotation:Rotation;
  scale:Scale;
  matrix:[Matrix];
  components:[Component];
}

table Subject {
  nodes:[Transform];
  name:string;
  x_axis:Direction;
  y_axis:Direction;
  z_axis:Direction;
  format:string;
  uuid:string;  // unique identifier, so name can be changed
  type:string;  // performer or prop
}

table SubjectUpdate {
  translations:[TranslationUpdate];
  rotation:[RotationUpdate];
  scale:[ScaleUpdate];
  uuid:string;
}

table Camera {
  uuid:string;
  transform:Transform;  
  filmback_width:float;
  filmback_height:float;
}

table CameraUpdate {
  focal_length:float;
  aspect:float;
  focus_distance:float;
  aperture:float;
  translation:Translation;
  rotation:Rotation;
  uuid:string;
}

table SubjectList {
   subjects:[Subject];
   updates:[SubjectUpdate];
   cameras:[Camera];
   cameras_updates:[CameraUpdate];
   time:double;
   timecode:string;
}

root_type SubjectList;