name: linux
on: [push, pull_request]
jobs:

  build:
    name: build
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      # Ensure submodules are fetched
      with:
        submodules: 'recursive'

    - name: Get Tools
      run: sudo apt-get install -y cmake ninja-build libmbedtls-dev        

    - name: NNG
      working-directory: thirdparty/nng
      run: |
        mkdir -p $RUNNER_TEMP/usr
        cmake -B build -G Ninja -DNNG_ENABLE_TLS=ON -DCMAKE_INSTALL_PREFIX=$RUNNER_TEMP/usr
        cmake --build build
        cmake --install build

    - name: CML
      working-directory: thirdparty/cml
      run: |
        cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$RUNNER_TEMP/usr
        cmake --build build
        cmake --install build        

    - name: CRC
      working-directory: thirdparty/crccpp
      run: |
        cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$RUNNER_TEMP/usr
        cmake --build build
        cmake --install build

    - name: FlatBuffers
      working-directory: thirdparty/flatbuffers
      run: |
        cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$RUNNER_TEMP/usr
        cmake --build build
        cmake --install build        

    - name: Open3DStream
      run: |
        cmake -B build -G Ninja -D NNG_ENABLE_TLS=ON -DCMAKE_PREFIX_PATH=$RUNNER_TEMP/usr
        cmake --build build
        cmake --install build
